### ISSUE TITLE
Not working from Xcode 7 

### ISSUE THREAD

**Issue by hardikdevios** [yeahdongcn/CocoaControlsPlugin#6]
please update the Plugin

**Comment by yeahdongcn** [comment]
Fixed by the following commits.

https://github.com/yeahdongcn/CocoaControlsPlugin/commit/b2681017d04f5503f44d79ad399b2988196522ff
https://github.com/yeahdongcn/CocoaControlsPlugin/commit/fd600a591c7803cb17cd198112a75731238d7646
